# RPC Server Configuration
rpcserverip=127.0.0.1
rpcserverport=8000
zookeeperip=127.0.0.1
zookeeperport=2181

# Redis Configuration
redisip=127.0.0.1
redisport=6379
redispassword=

# Rate Limiting Configuration
ratelimitalgorithm=3
ratelimitmaxqps=1000
ratelimitwindowsec=1
ratelimitenableprovider=false
ratelimitenableconsumer=false

# Metrics Configuration
metricsenable=true
