# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: friend.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import user_pb2 as user__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='friend.proto',
  package='fixbug',
  syntax='proto3',
  serialized_options=b'\200\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x66riend.proto\x12\x06\x66ixbug\x1a\nuser.proto\"#\n\x11\x46riendlistRequest\x12\x0e\n\x06userid\x18\x01 \x01(\r\"I\n\x12\x46riendlistResponse\x12\"\n\x06result\x18\x01 \x01(\x0b\x32\x12.fixbug.ResultCode\x12\x0f\n\x07\x66riends\x18\x02 \x03(\x0c\x32Z\n\x10\x46riendServiceRpc\x12\x46\n\rGetFriendlist\x12\x19.fixbug.FriendlistRequest\x1a\x1a.fixbug.FriendlistResponseB\x03\x80\x01\x01\x62\x06proto3'
  ,
  dependencies=[user__pb2.DESCRIPTOR,])




_FRIENDLISTREQUEST = _descriptor.Descriptor(
  name='FriendlistRequest',
  full_name='fixbug.FriendlistRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userid', full_name='fixbug.FriendlistRequest.userid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=71,
)


_FRIENDLISTRESPONSE = _descriptor.Descriptor(
  name='FriendlistResponse',
  full_name='fixbug.FriendlistResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='fixbug.FriendlistResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='friends', full_name='fixbug.FriendlistResponse.friends', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=146,
)

_FRIENDLISTRESPONSE.fields_by_name['result'].message_type = user__pb2._RESULTCODE
DESCRIPTOR.message_types_by_name['FriendlistRequest'] = _FRIENDLISTREQUEST
DESCRIPTOR.message_types_by_name['FriendlistResponse'] = _FRIENDLISTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FriendlistRequest = _reflection.GeneratedProtocolMessageType('FriendlistRequest', (_message.Message,), {
  'DESCRIPTOR' : _FRIENDLISTREQUEST,
  '__module__' : 'friend_pb2'
  # @@protoc_insertion_point(class_scope:fixbug.FriendlistRequest)
  })
_sym_db.RegisterMessage(FriendlistRequest)

FriendlistResponse = _reflection.GeneratedProtocolMessageType('FriendlistResponse', (_message.Message,), {
  'DESCRIPTOR' : _FRIENDLISTRESPONSE,
  '__module__' : 'friend_pb2'
  # @@protoc_insertion_point(class_scope:fixbug.FriendlistResponse)
  })
_sym_db.RegisterMessage(FriendlistResponse)


DESCRIPTOR._options = None

_FRIENDSERVICERPC = _descriptor.ServiceDescriptor(
  name='FriendServiceRpc',
  full_name='fixbug.FriendServiceRpc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=148,
  serialized_end=238,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetFriendlist',
    full_name='fixbug.FriendServiceRpc.GetFriendlist',
    index=0,
    containing_service=None,
    input_type=_FRIENDLISTREQUEST,
    output_type=_FRIENDLISTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FRIENDSERVICERPC)

DESCRIPTOR.services_by_name['FriendServiceRpc'] = _FRIENDSERVICERPC

# @@protoc_insertion_point(module_scope)
